### ISSUE TITLE
[v0.11.0] Tests fail to build

### ISSUE THREAD

**Issue by jbeich** [AOMediaCodec/libavif#1162] opened 2022-10-14 21:12 UTC
Regressed by b3e0f315fcf9

```
$ c++ --version
FreeBSD clang version 14.0.5 (https://github.com/llvm/llvm-project.git llvmorg-14.0.5-0-gc12386ae247c)
Target: x86_64-unknown-freebsd14.0
Thread model: posix
InstalledDir: /usr/bin
```
```
$ cmake -DAVIF_BUILD_TESTS=on -B /tmp/libavif_build -G Ninja
$ cmake --build /tmp/libavif_build
[...]
FAILED: tests/avifmetadatatest
: && /usr/bin/c++   tests/CMakeFiles/aviftest_helpers.dir/gtest/aviftest_helpers.cc.o tests/CMakeFiles/avifmetadatatest.dir/gtest/avifmetadatatest.cc.o -o tests/avifmetadatatest  -Wl,-rpath,/usr/local/lib:/tmp/libavif_build  /usr/local/lib/libgtest.so.1.12.1  libavif_apps.a  libavif.so.15.0.0  -lm  /usr/local/lib/libpng.so  /usr/lib/libz.so  /usr/local/lib/libjpeg.so  -pthread && :
ld: error: undefined symbol: avifImageExtractExifOrientationToIrotImir
>>> referenced by avifmetadatatest.cc
>>>               tests/CMakeFiles/avifmetadatatest.dir/gtest/avifmetadatatest.cc.o:(libavif::(anonymous namespace)::MetadataTest_ExifIfdOffsetLoopingTo8_Test::TestBody())
c++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by wantehchang** [comment] 2022-10-14 21:54
Jan: Thank you for the bug report. I think I reproduced this bug locally. `tests/avifmetadatatest` must be linked with the static libavif library. I will try to figure out a solution.

A workaround is to pass `-DAVIF_BUILD_APPS=OFF -DAVIF_ENABLE_GTEST=OFF` to cmake. Since `-DAVIF_BUILD_APPS=OFF` is the default, it can be omitted.

Note: When creating the v0.11.0 release, I announced a release candidate (v0.11.0-rc1) two days ago (Wed Oct 12) to try to avoid this kind of build failure. Did you test the release candidate? If you only tested the final release, do you have any suggestions on how to publicize the release candidate better? Should I allow more days for people to test the release candidate?

Thanks.

**Comment by jbeich** [comment] 2022-10-14 22:15
> Did you test the release candidate?

No, due to lack of time. It usually consists of adjusting adjusting package glue, testing on all supported OS release/arch tuples, testing various build options, testing build of all consumers (currently: efl, kimageformats, darktable, sdl2_image) and testing runtime (via tests and/or CLI tools + pixbuf plugin). If the window between RC and final is short there's not point to rush only to repeat the same in a few days.

> do you have any suggestions on how to publicize the release candidate better?

`v0.11.0-rc1` is missing on [releases page](https://github.com/AOMediaCodec/libavif/releases). GitHub -> Watch -> Releases doesn't notify about random new tags, only those annotated as releases. For example, I subscribe to all upstream release notifications for packages I maintain.

**Comment by jbeich** [comment] 2022-10-14 22:16
Err, GitHub project page -> Watch -> Custom -> Releases. GitLab has a similar feature.

**Comment by wantehchang** [comment] 2022-10-14 22:49
Jan: Could you please test https://github.com/AOMediaCodec/libavif/pull/1163?

Thank you for mentioning the releases page. I noticed that the releases in the releases page can be marked as a pre-release, so we can announce release candidates there as pre-releases.

I will consider giving people more time to test a release candidate. We should add a CI build that builds libavif as a shared library.

**Comment by jbeich** [comment] 2022-10-14 23:01
I confirm, after applying #1163 tests built fine on FreeBSD amd64.

**Comment by y-guyon** [comment] 2022-10-17 13:19
> We should add a CI build that builds libavif as a shared library.

https://github.com/AOMediaCodec/libavif/pull/1170 is an attempt.

**Closed** 2022-10-17 17:47 UTC
