### ISSUE TITLE
Broken lossless decoding with XnViewMP or Firefox (and Chrome?)

### ISSUE THREAD

**Issue by gitoss** [AOMediaCodec/libavif#243] opened 2020-07-21 21:50 UTC
When I lossless-encode rgba png or rgb jpeg with avifenc 0.8 and view it in either Firefox (current Nightly 80) or XnViewMP (0.96.4) the colors are off and alpha and black are displayed as green. I didn't try Chrome yet.

It probably isn't a problem of the encoder, since avifdec'ing back results in the correct image => but you are more qualified to figure out what is wrong with the decoding lib and probably file bug reports?

By the way: "We don't support that file type" when trying to attach an avif image :->

**Comment by joedrago** [comment] 2020-07-21 21:53
I'm not sure what those decoder paths are doing, but a common trend with other implementations is their inability to handle certain legal combinations of settings, such as YUV444, or perhaps full range. I know Microsoft's implementation (if you open an AVIF in MSPaint) doesn't support 444 properly yet.

Do things look different/better if you add `--yuv 420` to the avifenc commandline?

**Comment by joedrago** [comment] 2020-07-21 21:53
Note: This will ruin "lossless".

**Comment by joedrago** [comment] 2020-07-21 21:57
Another possibility is simply that they aren't properly handling CICP matrix coefficients of Identity(0), which is the only way you can get lossless in an AVIF without increasing the bit depth of the image. It is most certainly legal to signal this in an AVIF, so if they display wrong, those decoder pipelines should fix it.

Aside: I'd say I see more interest and concerns about lossless AVIF than almost _anything else_ on here. What is your interest specifically in AVIF as a _lossless_ format?

**Comment by gitoss** [comment] 2020-07-21 22:08
I'd like to future-proof archive my digital camera images and still use them as-is, i.e. in image viewers and web browsers. This level of support will only happen with very popular formats, so probably jpeg-xl won't achieve this (knock on wood).

I'd like to have something with >8bit depth and better compression than png or tiff (well, libaom 2.0 is worse atm, but might get better sooner or later). Lossless webp (this isn't the vp8 codec, but an addon) has excellent compression and wide support, but limited to 8bit - so avif with 10/12 bit would be perfect.

**Comment by gitoss** [comment] 2020-07-21 22:13
Adding --yuv 420 doesn't change the problem :-\

I forgot to write: XnView displays alpha correctly in rgba (but colors are off), while black is green in the rgb image in either XnView or Firefox.

**Comment by tdaede** [comment] 2020-07-21 22:16
This is tracked in Firefox as https://bugzilla.mozilla.org/show_bug.cgi?id=1553289

**Comment by joedrago** [comment] 2020-07-21 22:16
Okay, just to pin down the issues further, `--lossless` is really somewhat shorthand for `--min 0 --max 0 --cicp 1/13/0 --yuv 444 --range full`. How do these commandlines fair (note, these are _not_ lossless):

`avifenc --min 0 --max 0 --yuv 420 --range full src.png dst_420_full.avif`
`avifenc --min 0 --max 0 --yuv 444 --range full src.png dst_444_full.avif`
`avifenc --min 0 --max 0 --yuv 420 --range limited src.png dst_420_limited.avif`
`avifenc --min 0 --max 0 --yuv 444 --range limited src.png dst_444_limited.avif`

**Comment by joedrago** [comment] 2020-07-21 22:19
That Firefox issue just sounds like they don't handle CICP `x/x/0` (identity) at all yet.

**Comment by gitoss** [comment] 2020-07-21 22:56
I'm using this test image: https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/RGB_color_wheel_36.svg/1200px-RGB_color_wheel_36.svg.png

XnView: all images are ok.

Firefox: 'limited' and 'full' are the same, either with 420 or 444. All colors are off compared to the source png, but in different color ranges - I'll try to attach browser screenshots. It's proably the bug linked above?

Btw encoding and decoding webp lossless or lossy works fine.

**Comment by joedrago** [comment] 2020-07-21 23:01
My guess for Firefox is that they're not honoring the CICP values at all, and are probably defaulting to BT601 coefficients (5/6) instead of BT709 (1). You can probably confirm this if  `--cicp 1/13/5` has more accurate colors for you.

WebP is probably using the official WebP library in all of these cases. I imagine if XnViewMP and Firefox both used libavif v0.8.0 we'd be in a similar state. AVIF is still in its infancy with regards to adoption and implementations.

**Comment by gitoss** [comment] 2020-07-21 23:08
Ok, avif is a new format and I'm not in a hurry ... after trying a lot of image formats over a couple of years :-o

I hope libavif gets adapted as "the" decoding lib for av1 images and these problems will go away sooner or later - and now there's a bugticket over here, too, so people wondering about the same thing can find it.

**Comment by tdaede** [comment] 2020-07-21 23:50
Firefox is supposed to honor the CICP values, and does at least for VP9. Could you attach example images (ideally with the correct decoding result) and I can file a corresponding Firefox bug?

**Comment by gitoss** [comment] 2020-07-22 06:04
The github attachment upload doesn't work for me, here is the link to a file sharing service (ads, but it doesn't hack your twitter account) with the source image, avif lossless, debugging 420/444 (see above) plus screenshots from the resulting firefox decoder: http://www.filedropper.com/ff-avif-decoding-bug

**Comment by tdaede** [comment] 2020-07-22 06:37
The RGB matrix is working OK.
I have filed two bugs on the remaining issues:
Full range coefficients: https://bugzilla.mozilla.org/show_bug.cgi?id=1654461
Alpha: https://bugzilla.mozilla.org/show_bug.cgi?id=1654462

**Comment by gitoss** [comment] 2020-07-22 09:03
Thanks for filing the bug reports with Mozilla. Do these cover black in lossless mode displayed as green? http://www.filedropper.com/ff-avif-decoding-bug2

**Comment by tdaede** [comment] 2020-07-22 16:16
That one is not a bug - it's tagged unspecified for its primaries and matrix. What tool did you use to create that file?

**Comment by joedrago** [comment] 2020-07-22 16:26
I'm seeing CICP 2/2/0 for that last one, which should be interpreted as GBR with an unspecified color profile. That isn't incorrect. I assume they used avifenc for that one.

**Comment by gitoss** [comment] 2020-07-22 16:57
> 
> 
> That one is not a bug - it's tagged unspecified for its primaries and matrix. What tool did you use to create that file?

I'm using the official(tm) release win-x64 from the releases page.... simply by using avifenc.exe --lossless

**Comment by tdaede** [comment] 2020-07-22 18:22
Oh ok. I'm not entirely sure why firefox is actually using RGB for the color wheel one, but not the test pattern one - maybe the presence of the alpha channel causes it? Regardless, it's a bug.

**Comment by vrabaud** [comment] 2023-12-01 15:56
All reported bugs seems fixed in Firefox

**Closed by vrabaud** 2023-12-01 15:56 UTC
