### ISSUE TITLE
Memory allocation failures are not checked and handled.

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#103] opened 2020-03-09 19:19 UTC
Libavif does not check and handle memory allocation failures. Here is an example in src/avif.c:

avifImage * avifImageCreate(int width, int height, int depth, avifPixelFormat yuvFormat)
{
    avifImage * image = (avifImage *)avifAlloc(sizeof(avifImage));
    avifImageSetDefaults(image);
    image->width = width;
    image->height = height;
    image->depth = depth;
    image->yuvFormat = yuvFormat;
    return image;
}

Note that 'image' is dereferenced without a null pointer check.

This policy is acceptable to some clients. For example, in Chromium any memory allocation failure aborts the process. On the other hand, this policy would be a dealbreaker to clients that try to handle memory allocation failures.

If this policy is deliberate, it should be documented. Otherwise, we should add code to check for and  report out-of-memory errors. Some functions such as avifImageAllocatePlanes() that allocate memory and return void will need to return avifBool instead.

**Comment by joedrago** [comment] 2020-03-09 23:25
I hadn't planned to catch failures to allocate memory, and while I'm sure I could plumb a lot of that through, I'd prefer not to (I could be convinced otherwise).

If I chose not to, how/where would you expect such documention to be?

**Comment by wantehchang** [comment] 2020-03-09 23:38
README.md seems like a good place to document this policy. (It is the only .md file in the source tree.) Another good place would be the public header include/avif/avif.h.

**Comment by AurelC2G** [comment] 2020-05-27 15:29
Any chance we can revisit this decision? On mobile especially we can run into situations when the available memory is very limited, and right now the current behavior of libavif would lead to hard-to-debug crashes due to memory corruption. Probably better to explicitly error out if an allocation failed.

**Comment by joedrago** [comment] 2020-05-27 16:45
I can add `AVIF_RESULT_OUT_OF_MEMORY` and do an audit pass, trying to catch all calls to `avifAlloc()` and `avifArrayPushPtr()`. If I manage to catch them all, perhaps I'll change the policy to enforce this.

**Comment by AurelC2G** [comment] 2020-06-01 13:54
Alternatively, we could at least `abort()` within `avifAlloc` if `malloc` failed. This way we avoid undefined behavior of just dereferencing these null pointers.

**Comment by 0xC0000054** [comment] 2020-06-04 01:34
> Alternatively, we could at least abort() within avifAlloc if malloc failed. This way we avoid undefined behavior of just dereferencing these null pointers.

I think that rav1e may already do this, based on the fact that Rust currently aborts the process when a memory allocation fails (see https://github.com/rust-lang/rust/issues/43596) and the lack of an out-of-memory error code in the C API.

While calling `abort()` is preferable to derefrencing a null pointer, there are some use cases where it would be unacceptable to terminate the process.
For example, libavif could not be used by to create an AVIF plugin for Adobe Photoshop because Photoshop plugins are loaded in-process, and terminating Photoshop on out-of-memory would cause the user to loose all of their images that have unsaved changes.

> I can add AVIF_RESULT_OUT_OF_MEMORY and do an audit pass, trying to catch all calls to avifAlloc() and avifArrayPushPtr(). If I manage to catch them all, perhaps I'll change the policy to enforce this.

As I mentioned above, this would depend on the behavior of the individual codecs.
It appears that AOM and dav1d return an error code for out-of-memory, so you may just have to verify and document which codecs support allowing the caller to handle out-of-memory conditions.

**Comment by AurelC2G** [comment] 2020-06-04 08:48
The problem is not so much about the allocations performed by the codecs (out of scope for this repository), but the allocations performed by libavif itself.

> While calling abort() is preferable to derefrencing a null pointer, there are some use cases where it would be unacceptable to terminate the process.
For example, libavif could not be used to create an AVIF plugin for Adobe Photoshop because Photoshop plugins are loaded in-process, and terminating Photoshop on out-of-memory would cause the user to lose all of their images that have unsaved changes.

I agree that abort is not ideal compared to reporting the errors and letting client code handle them. However, the current version is even worse, dereferencing a null pointer is undefined behavior so the outcome could be anything (including terminating the process).

**Closed** 2020-06-24 14:51 UTC
