### ISSUE TITLE
Problem with svt-av1

### ISSUE THREAD

**Issue by Jamaika1** [AOMediaCodec/libavif#739] opened 2021-08-22 14:58 UTC
Hi
I don't know how to properly compile the asm codec. It doesn't see sse2 and want to create photos.
New fixes libavif/heif
I added new fixes to add ARCH_X86_64 in assembler for dav1d and svt-av1.
https://gitlab.com/AOMediaCodec/SVT-AV1/-/commit/09555148333e849ce5f04f891672a86304149e47
avifenc.exe -c svt -d 8 -y 420 -r limited -s 5 -j 4 image_21447_24bit.jpg image_21447_24bita.avif
Problem with memory SVT-AV1 by big files JPG
Error Instance 1: Source Height must be even for YUV_420 colorspace
ERROR: Failed to encode image: Encoding of color planes failed
SvtMalloc[info]: you have no memory leak
Problem with asm for only sse2
[asm level on system : up to avx]
https://www.sendspace.com/file/bkjqek

**Comment by 1480c1** [comment] 2021-08-22 15:14
Odd dimensions issue is a duplicate of https://github.com/AOMediaCodec/libavif/issues/544

**Comment by Jamaika1** [comment] 2021-08-22 16:59
I added 4000x3000 photo. Doesn't want to work.

**Comment by joedrago** [comment] 2021-08-23 17:18
The `-a` commandline argument is simply passing key/value pairs to the underlying AV1 codec, and it is up to that codec's implementation to leverage those values (via `codec->csOptions`). The implementation in `codec_svt.c` currently doesn't leverage these options.

**Comment by Jamaika1** [comment] 2021-08-23 19:06
Thanks for the answer. Maybe add some info that the option is unsupported.

Who knows? Is it worth adding assembler to sse2 or vice versa it is harmful activity. 
nasm.exe -f win64 -O3 -DWIN64=1 -D__x86_64__=1 -DPIC=1 file.asm -Xgnu -o file.o

**Comment by joedrago** [comment] 2021-08-23 19:36
> Maybe add some info that the option is unsupported.

The settings you attempted to use are under the `aom-specific advanced options` heading, which don't apply when you use SVT. Please see avifenc's syntax for more information.

**Closed** 2022-03-20 06:34 UTC
