### ISSUE TITLE
“enable-qm=1” and “denoise-noise-level=5” output a corrupted image

### ISSUE THREAD

**Issue by sommio** [AOMediaCodec/libavif#1658] opened 2023-10-06 00:37 UTC
They work fine in ffmpeg

**Information**
libavif 1.0.1-1.1 (via [ALHP](https://somegit.dev/ALHP/ALHP.GO))
ffmpeg 2:6.0-11.1 (via [ALHP](https://somegit.dev/ALHP/ALHP.GO))
aom-av1-lavish-git r33040.83500ccf3-1 (via [AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=aom-av1-lavish-git) branch=Endless_Merging)
```
ffmpeg version n6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.2.1 (GCC) 20230801
  configuration: --prefix=/usr --disable-debug --disable-static 
  --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm
  --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl
  --enable-ladspa --enable-libaom --enable-libass --enable-libbluray
  --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libfreetype
  --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack
  --enable-libjxl --enable-libmodplug --enable-libmp3lame
  --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg
  --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librav1e
  --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt
  --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2
  --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpl
  --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265
  --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg
  --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl
  --enable-shared --enable-version3 --enable-vulkan

  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
```

**Reproduction**
```
avifenc -j 3 -s 3 -a end-usage=cq -a cq-level=18 \
-a enable-qm=1 image.png image_avifenc_qm.avif
```
```
avifenc -j 3 -s 3 -a end-usage=cq -a cq-level=18 \
-a denoise-noise-level=5 image.png image_avifenc_noise.avif
```

```
ffmpeg -i image.png -c:v libaom-av1 -threads 3 -cpu-used 3 \
-crf 18 -aom-params enable-qm=1 image_ffmpeg_qm.avif
```
```
ffmpeg -i image.png -c:v libaom-av1 -threads 3 -cpu-used 3 \
-crf 18 -aom-params denoise-noise-level=5 image_ffmpeg_noise.avif
```

[**Samples.zip**](https://pixeldrain.com/u/GxHGMAwN) Download

**Comment by jzern** [comment] 2023-10-06 01:31
Thanks for the report. Could you also provide the avifenc version as well as the libaom version used by it and ffmpeg?

**Comment by sommio** [comment] 2023-10-06 08:54
Sorry, I just added the information

**Comment by vigneshvg** [comment] 2023-10-06 18:42
I tried the exact `avifenc` commands mentioned in the first comment and i was not able to reproduce the failure.

both the commands generate valid AVIF files for me.

Here are the library versions i used:
libavif - `ee29bec`
libaom - `2603b3a2d`

We have not looked into `aom-av1-lavish-git` fork of aom and it is not one of the officially supported libraries in libavif. So can you please try encoding again with the official version of libaom?

The error in your files seems to be from the alpha planes (which is why the ffmpeg encoded variants are okay because ffmpeg ignores the alpha planes by default). So my best guess here is that the `aom-av1-lavish-git` fork is producing invalid output when encoding alpha planes (monochrome images).

**Comment by sommio** [comment] 2023-10-06 18:57
Thank you vigneshvg, official aomenc no problem. 
can avifenc ignore alpha planes like ffmpeg?

**Comment by vigneshvg** [comment] 2023-10-06 19:07
I was able to link libavif against aom-av1-lavish-git and using that reproduces your failures. The fork seems to be lagging behind libaom by around 900 commits.

So this is not a bug in libavif. Updating the fork is likely what is needed here.

> can avifenc ignore alpha planes like ffmpeg?

ffmpeg actually ignores the alpha planes. avifenc does the right thing in that if the input PNG file contains an alpha plane, it encodes them into the AVIF file as well. if you want to ignore the alpha plane, then you would have to convert the PNG file into a PNG file without alpha first and then pass it to avifenc.

For example, you can convert the `image.png` to remove the alpha channel like so:
ffmpeg -i image.png -pix_fmt rgb48be image_without_alpha.png
avifenc -j 3 -s 3 -a end-usage=cq -a cq-level=18 -a denoise-noise-level=5 image_without_alpha.png image_avifenc_noise.avif

I verified these commands and they produce valid AVIF images even with the `aom-av1-lavish-git` fork.

Closing this issue. Please feel free to re-open if you have further questions.

**Closed by vigneshvg** 2023-10-06 19:07 UTC

**Comment by sommio** [comment] 2023-10-06 20:50
Problem solved, my ss is generated via [mpv](https://mpv.io/manual/master/#options-screenshot-high-bit-depth).
It contained unused alpha channels, which may be the cause of the `aom-av1-lavish` failure.
> --screenshot-high-bit-depth=<yes|no>
> If possible, write screenshots with a bit depth similar to the source video (default: yes).
> This is interesting in particular for PNG, as this sometimes triggers writing 16 bit PNGs with huge file sizes.
> This will also include an unused alpha channel in the resulting files if 16 bit is used.

Encoding [W3 Alpha Test PNG](https://www.w3.org/Graphics/PNG/Alphatest.html) everything is fine

**Comment by vigneshvg** [comment] 2023-10-06 20:56
Great, glad you were able to figure it out.

I will also consider adding an option to `avifenc` which can be used to ignore the alpha channels in such files (i.e.) something like `--ignore-alpha` or `--no-alpha` so that such PNG files can be encoded with `avifenc` directly without having to use an external tool to remove the alpha channel. (Filed https://github.com/AOMediaCodec/libavif/issues/1665 for this).

**Comment by wantehchang** [comment] 2023-10-06 23:30
If the alpha channel in `image.png` is fully opaque, avifenc should be able to detect that and ignore it.

Do you know if the alpha channel is fully opaque?

**Comment by vigneshvg** [comment] 2023-10-06 23:35
> If the alpha channel in `image.png` is fully opaque, avifenc should be able to detect that and ignore it.
> 
> Do you know if the alpha channel is fully opaque?

avifenc is not ignoring it. So it probably isn't opaque.

**Comment by sommio** [comment] 2023-10-07 00:55
```convert image.png -channel A -separate image.a.png```

![image a](https://github.com/AOMediaCodec/libavif/assets/64189793/6665c3ea-7131-48e5-b8b0-0a4d4ad3a986)

I hope this helps.
