### ISSUE TITLE
Enabling chroma-delta quantization breaks the aomenc's color output in AVIF intra only

### ISSUE THREAD

**Issue by BlueSwordM** [AOMediaCodec/libavif#733] opened 2021-08-07 16:55 UTC
**What steps will reproduce the problem?**
1. Build aom-master using the release profile

2. Encode any video/image using aomenc separately or aomenc as part of avifenc using default settings. After, do the same but with chroma-deltaq enabled(--enable-chroma-deltaq=1 in aomenc, and -a color:enable-chroma-deltaq=1 inside of avifenc), and then compare against the original.

**What is the expected output?**
Similar visual output.

What do you see instead?
In intra only, the image is severely tinted to pink.

In video, the problem is less severe, but it is still present

What version / commit were you testing with? (git describe can produce this
info if building from source). On what operating system?

Latest aom-git master(3.1.2-566-ge18c89426 and 3.1.2-604-g3e8f2795b) 
Tested on:
OpenMandriva Cooker
Ubuntu 21.04
Windows 10

Please provide any additional information below.
This bug seems to have been introduced very recently as of Friday the 23rd. aomenc 3.1.2 stable seems to not have this issue, but a few commits after seems to have broken it.

Changing the speed level also changes the kind of chroma shift observed.

Intra images are affected more than inter codec frames.

Source example:
https://bugs.chromium.org/p/aomedia/issues/attachment?aid=512581&signed_aid=LMSoGS9onn1Fw79Uc9mRHA==

**Comment by joedrago** [comment] 2021-08-07 18:05
Thank you for the bug report  but this issue is very likely to be something in the internals of libaom, which is a different codebase/repo (and team):

https://aomedia.googlesource.com/aom/

I think we should keep this issue open so we know when to bump the version when they fix it, but can you please file a similar report with them so they can fix their issue?

**Comment by BlueSwordM** [comment] 2021-08-07 18:12
I have already filed a similar report on the aomedia issue, but it seems to have been ignored, which is why I posted it here:
https://bugs.chromium.org/p/aomedia/issues/detail?id=3117

I know a few aom devs hang out here, which is why I posted it here.

**Comment by joedrago** [comment] 2021-08-07 18:15
Ah, yes, @wantehchang is a regular contributor for both projects, but I believe he is unavailable for a bit. I hadn't planned on releasing a new version of libavif for a little while anyway (as we did a release recently), but I will definitely hold off on another release until this issue is resolved.

**Comment by wantehchang** [comment] 2021-08-07 23:08
Hi Zak,

Thanks a lot for the bug report. I have reproduced the bug and tracked down the libaom commit that introduced the bug. Let's continue the discussion in the libaom issue (https://bugs.chromium.org/p/aomedia/issues/detail?id=3117).

Joe: We can close this libavif issue because the current libaom release (v3.1.2) does not have this bug. This bug is only in the prerelease libaom master branch.

**Closed by wantehchang** 2021-08-07 23:08 UTC

**Comment by BlueSwordM** [comment] 2021-08-08 00:27
Thanks a lot for your support wtc.

Sorry if I bothered you in that regard. I'm happy to help still.

**Comment by wantehchang** [comment] 2021-08-08 01:42
Hi Zak,

You didn't bother me at all. I am sorry for the late response. If you could verify the results of my bisection and post a comment in https://bugs.chromium.org/p/aomedia/issues/detail?id=3117, I would appreciate it.
