### ISSUE TITLE
Avifenc fails to process files with non UTF8 file names

### ISSUE THREAD

**Issue by hlad12** [AOMediaCodec/libavif#1238] opened 2022-12-05 14:15 UTC
Avifenc fails to process files with non UTF8 file names, having nonstandard characters like Russian / Hindi characters in their file names

**Comment by y-guyon** [comment] 2022-12-05 14:20
Thank you for the report.
May I know on which platform you are encountering the issue?
Do you have a file that you can upload here (keeping the file name or zipping it) to reproduce the issue?

**Comment by wantehchang** [comment] 2022-12-07 22:15
@hlad12 Since you didn't mention avifdec in this bug report, I only inspected avifenc.c.

One thing that may go wrong is the first line in the `avifReadImage()` function:

```
    const avifAppFileFormat format = avifGuessFileFormat(filename);
```

The bug may be in the following code in `avifGuessFileFormat()`:

```
    // If we get here, the file header couldn't be read for some reason. Guess from the extension.

    const char * fileExt = strrchr(filename, '.');
    if (!fileExt) { 
        return AVIF_APP_FILE_FORMAT_UNKNOWN;
    }
    ++fileExt; // skip past the dot

    char lowercaseExt[8]; // This only needs to fit up to "jpeg", so this is plenty
    const size_t fileExtLen = strlen(fileExt);
    if (fileExtLen >= sizeof(lowercaseExt)) { // >= accounts for NULL terminator
        return AVIF_APP_FILE_FORMAT_UNKNOWN;
    }
    
    for (size_t i = 0; i < fileExtLen; ++i) {
        lowercaseExt[i] = (char)tolower((unsigned char)fileExt[i]);
    }
    lowercaseExt[fileExtLen] = 0;
    
    if (!strcmp(lowercaseExt, "avif")) {
        return AVIF_APP_FILE_FORMAT_AVIF;
    } else if (!strcmp(lowercaseExt, "y4m")) {
        return AVIF_APP_FILE_FORMAT_Y4M;
    } else if (!strcmp(lowercaseExt, "jpg") || !strcmp(lowercaseExt, "jpeg")) {
        return AVIF_APP_FILE_FORMAT_JPEG;
    } else if (!strcmp(lowercaseExt, "png")) {
        return AVIF_APP_FILE_FORMAT_PNG;
    } 
    return AVIF_APP_FILE_FORMAT_UNKNOWN;
```

**Comment by mintommm** [comment] 2023-10-09 07:31
I also faced this issue.
Encoding seems to fail if emoji is included in the path.

OS: Windows 11 Pro 22H2
Terminal: PowerShell 7.3.7
Binary: avifenc.exe from https://ci.appveyor.com/project/louquillio/libavif/build/artifacts
Original Image: Jy0O0q0mLXl668HAo43n.jpeg from https://web.dev/compress-images-avif/

If run it with the original name, it will succeed.
```
PS T:\emoji> .\avifenc.exe --version
Version: 1.0.1 (dav1d [dec]:1.2.1-0-g8a6f054, aom [enc/dec]:3.7.0-457-g2603b3a2d)
libyuv : available (1864)

PS T:\emoji> .\avifenc.exe .\Jy0O0q0mLXl668HAo43n.jpeg .\Jy0O0q0mLXl668HAo43n.avif
Directly copied JPEG pixel data (no YUV conversion): .\Jy0O0q0mLXl668HAo43n.jpeg
Successfully loaded: .\Jy0O0q0mLXl668HAo43n.jpeg
AVIF to be written: (Lossy)
 * Resolution     : 840x1120
 * Bit Depth      : 8
 * Format         : YUV420
 * Chroma Sam. Pos: 0
 * Alpha          : Absent
 * Range          : Full
 * Color Primaries: 1
 * Transfer Char. : 13
 * Matrix Coeffs. : 6
 * ICC Profile    : Absent
 * XMP Metadata   : Absent
 * Exif Metadata  : Absent
 * Transformations: None
 * Progressive    : Unavailable
Encoding with AV1 codec 'aom' speed [6], color quality [60 (Medium)], alpha quality [100 (Lossless)], tileRowsLog2 [0], tileColsLog2 [0], 1 worker thread(s), please wait...
Encoded successfully.
 * Color AV1 total size: 29981 bytes
 * Alpha AV1 total size: 0 bytes
Wrote AVIF: .\Jy0O0q0mLXl668HAo43n.avif
```

If change the name to `🐾.jpeg` and run it, it will fail.
```
PS T:\emoji> .\avifenc.exe .\🐾.jpeg .\🐾.avif
Can't open JPEG file for read: .\??.jpeg
Cannot read input file: .\??.jpeg
```

Attaching the image for reproduce.
GitHub does not allow to attach the file with original name, so please rename this file to `🐾.jpeg` before run it.
![🐾](https://github.com/AOMediaCodec/libavif/assets/1401820/43bcab75-8491-4d83-854c-1e36a25ebdaf)

**Comment by wantehchang** [comment] 2023-10-10 21:20
Note that in CMakeLists.txt, we have the following:

```
    add_compile_options(
        ...
        # This tells MSVC to read source code as UTF-8 and assume console can only use ASCII (minimal safe).
        # libavif uses ANSI API to print to console, which is not portable between systems using different
        # languages and results in mojibake unless we only use codes shared by every code page: ASCII.
        # A C4556 warning will be generated on violation.
        # Commonly used /utf-8 flag assumes UTF-8 for both source and console, which is usually not the case.
        # Warnings can be suppressed but there will still be random characters printed to the console.
        /source-charset:utf-8
        /execution-charset:us-ascii
    )
```

I found that the `/execution-charset:us-ascii` compiler flag does not seem to have an effect on this issue.

**Comment by wantehchang** [comment] 2024-05-09 16:54
This has been fixed by a series of commits from Vincent, including https://github.com/AOMediaCodec/libavif/pull/1693. Eventually we switched to a solution using a manifest file (https://github.com/AOMediaCodec/libavif/pull/1900).

**Closed by wantehchang** 2024-05-09 16:54 UTC
