### ISSUE TITLE
GIF encodes with wrong frame rate

### ISSUE THREAD

**Issue by xgretsch** [AOMediaCodec/libavif#2161] opened 2024-05-14 14:57 UTC
On one specific gif file, after processing via ffmpeg, the avifenc encoder produces an avif file which is correct in all respects other than its frame rate is wrong: instead of changing frames after 2 seconds like the gif does, it changes frames after a much longer period (over 10 seconds).

Here is some relevant terminal output:

From ffmpeg:
```
ffmpeg -i bugreport.gif -pix_fmt yuv420p -f yuv4mpegpipe bugreport.y4m
ffmpeg version 6.1.1-3ubuntu5 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13 (Ubuntu 13.2.0-23ubuntu3)
  configuration: --prefix=/usr --extra-version=3ubuntu5 --toolchain=hardened --libdir=/usr/lib/aarch64-linux-gnu --incdir=/usr/include/aarch64-linux-gnu --arch=arm64 --enable-gpl --disable-stripping --disable-omx --enable-gnutls --enable-libaom --enable-libass --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libharfbuzz --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-openal --enable-opencl --enable-opengl --disable-sndio --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-ladspa --enable-libbluray --enable-libjack --enable-libpulse --enable-librabbitmq --enable-librist --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libx264 --enable-libzmq --enable-libzvbi --enable-lv2 --enable-sdl2 --enable-libplacebo --enable-librav1e --enable-pocketsphinx --enable-librsvg --enable-libjxl --enable-shared
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
Input #0, gif, from 'bugreport.gif':
  Duration: 00:00:04.00, start: 0.000000, bitrate: 386 kb/s
  Stream #0:0: Video: gif, bgra, 400x400, 0.50 fps, 100 tbr, 100 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (gif (native) -> wrapped_avframe (native))
Press [q] to stop, [?] for help
Output #0, yuv4mpegpipe, to 'bugreport.y4m':
  Metadata:
    encoder         : Lavf60.16.100
  Stream #0:0: Video: wrapped_avframe, yuv420p(tv, progressive), 400x400, q=2-31, 200 kb/s, 100 fps, 100 tbn
    Metadata:
      encoder         : Lavc60.31.102 wrapped_avframe
[out#0/yuv4mpegpipe @ 0xaaaadbd7ec00] video:188kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 49901.291146%
frame=  400 fps=0.0 q=-0.0 Lsize=   93752kB time=00:00:03.99 bitrate=192486.2kbits/s dup=398 drop=0 speed=  29x    
```
The version of avifenc:
```
Version: 1.0.4 (dav1d [dec]:1.4.1, libgav1 [dec]:0.18.0, aom [enc/dec]:v3.8.2, rav1e [enc]:0.7.1 (UNKNOWN), svt [enc]:v1.7.0)
libyuv : available (1883)
```
Output from avifenc:
![bugreport](https://github.com/AOMediaCodec/libavif/assets/898362/9a881f13-4ba7-4c8d-955d-fe55ae826f57)

```
avifenc bugreport.y4m bugreport.avif
Successfully loaded: bugreport.y4m
AVIF to be written: (Lossy)
 * Resolution     : 400x400
 * Bit Depth      : 8
 * Format         : YUV420
 * Chroma Sam. Pos: 0
 * Alpha          : Absent
 * Range          : Limited
 * Color Primaries: 1
 * Transfer Char. : 13
 * Matrix Coeffs. : 6
 * ICC Profile    : Absent
 * XMP Metadata   : Absent
 * Exif Metadata  : Absent
 * Transformations: None
 * Progressive    : Unavailable
Encoding with AV1 codec 'aom' speed [6], color quality [60 (Medium)], alpha quality [100 (Lossless)], tileRowsLog2 [0], tileColsLog2 [0], 1 worker thread(s), please wait...
 * Encoding frame 1 [1/100 ts]: bugreport.y4m
 * Encoding frame 2 [1/100 ts]: bugreport.y4m
 * Encoding frame 3 [1/100 ts]: bugreport.y4m
 * Encoding frame 4 [1/100 ts]: bugreport.y4m
 * Encoding frame 5 [1/100 ts]: bugreport.y4m
...
 * Encoding frame 397 [1/100 ts]: bugreport.y4m
 * Encoding frame 398 [1/100 ts]: bugreport.y4m
 * Encoding frame 399 [1/100 ts]: bugreport.y4m
Encoded successfully.
 * Color AV1 total size: 210483 bytes
 * Alpha AV1 total size: 0 bytes
Wrote AVIF: bugreport.avif
```
![bugreport](https://github.com/AOMediaCodec/libavif/assets/898362/d54b6d3d-02af-4d80-ae05-dcff72ed1c15)
[bugreport.avif.zip](https://github.com/AOMediaCodec/libavif/files/15310256/bugreport.avif.zip)

**Comment by wantehchang** [comment] 2024-05-14 15:04
@xgretsch Thank you for the bug report.

Vignesh, could you take a look at this? Thanks.

**Comment by vigneshvg** [comment] 2024-05-15 17:11
For some reason, ffmpeg is not preserving the frame rate when converting the GIF to Y4M. If you look at the ffmpeg output:

```
Input #0, gif, from 'bugreport.gif':
  Stream #0:0: Video: gif, bgra, 400x400, 0.50 fps, 100 tbr, 100 tbn

Output #0, yuv4mpegpipe, to 'bugreport.y4m':
  Stream #0:0: Video: wrapped_avframe, yuv420p(tv, progressive), 400x400, q=2-31, 200 kb/s, 100 fps, 100 tbn
```

If i force the frame rate of the y4m conversion with `-r 1/2`, then the avif file's rate matches that of the GIF:
```
ffmpeg -i bugreport.gif -pix_fmt yuv420p -f yuv4mpegpipe -r 1/2 bugreport.y4m
```

I will take a look and see why ffmpeg is not respecting the GIF's frame rate. In the meantime this is the workaround.

**Comment by vigneshvg** [comment] 2024-05-15 17:54
Also, note that you can use ffmpeg to convert the GIF to AVIF directly while respecting the frame rate like so:

```
ffmpeg -i input.gif -fps_mode passthrough output.avif
```

**Comment by xgretsch** [comment] 2024-05-15 19:13
I can confirm that your workaround does the job. Many thanks! I assume I should leave the issue open, even though this will fix it for my purposes - but feel free to say otherwise.

**Comment by vigneshvg** [comment] 2024-05-15 19:16
Yeah, please leave it open. I will close it once i confirm why ffmpeg does not do this automatically.

**Comment by xgretsch** [comment] 2024-06-03 10:43
Just to keep me on my toes, I now have a different file on which the "passthrough" mode does not work, but for which my original script which went via a y4m intermediate is fine.

```
![bugreport2](https://github.com/AOMediaCodec/libavif/assets/898362/5f1d44d7-b74f-4978-a822-2829cd8f5bc4)
```

**Comment by xgretsch** [comment] 2024-06-03 10:44
Here's the output, which seems to have been lost from the previous post:

```
# ffmpeg -i bugreport2.gif -fps_mode passthrough bugreport2.avif
ffmpeg version 6.1.1-3ubuntu5 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13 (Ubuntu 13.2.0-23ubuntu3)
  configuration: --prefix=/usr --extra-version=3ubuntu5 --toolchain=hardened --libdir=/usr/lib/aarch64-linux-gnu --incdir=/usr/include/aarch64-linux-gnu --arch=arm64 --enable-gpl --disable-stripping --disable-omx --enable-gnutls --enable-libaom --enable-libass --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libharfbuzz --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-openal --enable-opencl --enable-opengl --disable-sndio --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-ladspa --enable-libbluray --enable-libjack --enable-libpulse --enable-librabbitmq --enable-librist --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libx264 --enable-libzmq --enable-libzvbi --enable-lv2 --enable-sdl2 --enable-libplacebo --enable-librav1e --enable-pocketsphinx --enable-librsvg --enable-libjxl --enable-shared
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
Input #0, gif, from 'bugreport2.gif':
  Metadata:
    comment         : GIF optimized with https://ezgif.com/optimize
  Duration: 00:00:10.00, start: 0.000000, bitrate: 160 kb/s
  Stream #0:0: Video: gif, bgra, 400x400, 0.50 fps, 0.50 tbr, 100 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (gif (native) -> av1 (libaom-av1))
Press [q] to stop, [?] for help
[libaom-av1 @ 0xaaaae58383d0] v3.8.2
[libaom-av1 @ 0xaaaae58383d0] Neither bitrate nor constrained quality specified, using default CRF of 32
[libaom-av1 @ 0xaaaae58383d0] aom_codec_enc_cfg
[libaom-av1 @ 0xaaaae58383d0] generic settings
  g_usage:                      0
  g_threads:                    10
  g_profile:                    1
  g_w:                          400
  g_h:                          400
  g_bit_depth:                  8
  g_input_bit_depth:            8
  g_timebase:                   {2/1}
  g_error_resilient:            0
  g_pass:                       0
  g_lag_in_frames:              35
[libaom-av1 @ 0xaaaae58383d0] rate control settings
  rc_dropframe_thresh:          0
  rc_end_usage:                 3
  rc_twopass_stats_in:          (nil)(0)
  rc_target_bitrate:            256
[libaom-av1 @ 0xaaaae58383d0] quantizer settings
  rc_min_quantizer:             0
  rc_max_quantizer:             63
[libaom-av1 @ 0xaaaae58383d0] bitrate tolerance
  rc_undershoot_pct:            25
  rc_overshoot_pct:             25
[libaom-av1 @ 0xaaaae58383d0] decoder buffer model
  rc_buf_sz:                    6000
  rc_buf_initial_sz:            4000
  rc_buf_optimal_sz:            5000
[libaom-av1 @ 0xaaaae58383d0] 2 pass rate control settings
  rc_2pass_vbr_bias_pct:        50
  rc_2pass_vbr_minsection_pct:  0
  rc_2pass_vbr_maxsection_pct:  2000
[libaom-av1 @ 0xaaaae58383d0] keyframing settings
  kf_mode:                      1
  kf_min_dist:                  0
  kf_max_dist:                  9999
[libaom-av1 @ 0xaaaae58383d0] tile settings
  tile_width_count:             0
  tile_height_count:            0
[libaom-av1 @ 0xaaaae58383d0] 
[libaom-av1 @ 0xaaaae58383d0] Failed to initialize encoder: Invalid parameter
[libaom-av1 @ 0xaaaae58383d0]   Additional information: g_timebase.num out of range [1..cfg->g_timebase.den]
[vost#0:0/libaom-av1 @ 0xaaaae5838090] Error while opening encoder - maybe incorrect parameters such as bit_rate, rate, width or height.
Error while filtering: Invalid argument
[out#0/avif @ 0xaaaae5832c00] Nothing was written into output file, because at least one of its streams received no packets.
frame=    0 fps=0.0 q=0.0 Lsize=       0kB time=N/A bitrate=N/A speed=N/A    
Conversion failed!
#
```

**Comment by vigneshvg** [comment] 2024-06-04 21:32
Thanks for the detailed bug report. I was able to reproduce it. This was a bug in libaom and i have sent a patch to fix it here: https://aomedia-review.googlesource.com/c/aom/+/190883

libaom currently doesn't allow an fps of < 1 and this input file has an fps of 0.5. You would have to wait for the patch to land and then update libaom to tip of tree for this to work.

**Comment by vigneshvg** [comment] 2024-06-04 21:40
In the meantime, the workaround is to use a different AV1 encoder like rav1e with ffmpeg. This command works for me:

```
ffmpeg -i bugreport2.gif -fps_mode passthrough -c:v librav1e output.avif
```

However, this does come with quality implications. Files produced by rav1e may or may not be as good as libaom.

**Comment by wantehchang** [comment] 2024-06-05 16:13
@xgretsch Thanks for the bug report. Vignesh's bug fix will be in the upcoming libaom v3.9.1 patch release. I will let you know when libaom v3.9.1 is available.

You are using libaom v3.8.2. Will you be able to upgrade to libaom v3.9.1 (when it is available)? Or do you need this bug fixed in a libaom v3.8.3 patch release?

**Comment by xgretsch** [comment] 2024-06-06 15:16
Hi Wan Teh - thanks for dealing with this.

I'm trying to keep my installations of third party libraries down to using the Linux package installer. I'm starting with Ubuntu 24.04, and then doing:
```
RUN apt-get install -y ffmpeg
RUN apt-get install -y libavif-bin
```
Either way, if I want to put in your fix, I guess I will have to hand-compile libaom (and possibly the other packages), in which case I might as well wait for v3.9.1. But I won't really know for sure until I try it for real and see whether it causes any knock-on problems with other packages - in which case a patch release would probably be better.

I'm out of town right now, so I won't be back in front of my dev system until Monday; I'll look further then at what's involved in the hand compile.

Meanwhile, adding the option `-enc_time_base demux` to `ffmpeg` appears to be resolving the problem - but if you think that's a terrible idea, please say!

**Comment by wantehchang** [comment] 2024-06-07 00:11
@xgretsch Thanks for the reply. I am working on a libaom v3.8.3 patch release for Linux distributions such as Ubuntu 24.04 that may want to stick with the libaom v3.8.x series for a while.

**Comment by wantehchang** [comment] 2024-06-11 22:19
@xgretsch The libaom v3.8.3 and v3.9.1 releases are available now. Vignesh's bug fix is in both of these releases.

@vigneshvg I think we can close this issue.

**Closed** 2024-06-11 23:13 UTC
