### ISSUE TITLE
MSYS/MinGW32: Linking error, undefined references to Nt file functions

### ISSUE THREAD

**Issue by LigH-de** [AOMediaCodec/libavif#2109] opened 2024-04-14 10:01 UTC
Compiling libavif in media-autobuild suite fails linking Windows NT file functions

Part of **build/libavif-git/build-32bit/ab-suite.build.log**
```
[38/39] Linking CXX executable avifdec.exe
FAILED: avifdec.exe 
C:\Windows\system32\cmd.exe /C "cd . && G:\MABS\msys64\mingw32\bin\ccache.exe  g++ -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1 -O3 -DNDEBUG -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1 -static-libgcc -static-libstdc++ CMakeFiles/avifdec.dir/apps/avifdec.c.o CMakeFiles/avifdec.dir/apps/utf8.rc.obj -o avifdec.exe -Wl,--out-implib,libavifdec.dll.a -Wl,--major-image-version,0,--minor-image-version,0  libavif_apps.a  libavif_internal.a  G:/MABS/msys64/mingw32/lib/libyuv.a  -lm  G:/MABS/local32/lib/libdav1d.a  G:/MABS/local32/lib/librav1e.a  G:/MABS/local32/lib/libaom.a  G:/MABS/local32/lib/libpng.a  G:/MABS/msys64/mingw32/lib/libz.a  G:/MABS/msys64/mingw32/lib/libjpeg.a  -lmingwthrd  -lmingwthrd  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.2.0/../../../../i686-w64-mingw32/bin/ld.exe: G:/MABS/local32/lib/librav1e.a(rav1e.std-0f2dcfa9b7d06be0.std.b1ab508cbb5ea0e2-cgu.0.rcgu.o.rcgu.o): in function `ZN3std3sys3pal7windows1c11NtWriteFile17h3ec844bf04e2bc5fE':
/rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\sys\pal\windows/c.rs:309:(.text+0x1fdbc): undefined reference to `NtWriteFile@36'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.2.0/../../../../i686-w64-mingw32/bin/ld.exe: G:/MABS/local32/lib/librav1e.a(rav1e.std-0f2dcfa9b7d06be0.std.b1ab508cbb5ea0e2-cgu.0.rcgu.o.rcgu.o): in function `ZN3std3sys3pal7windows6handle6Handle17synchronous_write17haf3615c8b036eea9E':

/rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\sys\pal\windows/handle.rs:314:(.text+0x1fe50): undefined reference to `RtlNtStatusToDosError@4'

collect2.exe: error: ld returned 1 exit status
[39/39] Linking CXX executable avifenc.exe
FAILED: avifenc.exe 
C:\Windows\system32\cmd.exe /C "cd . && G:\MABS\msys64\mingw32\bin\ccache.exe  g++ -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1 -O3 -DNDEBUG -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1 -static-libgcc -static-libstdc++ CMakeFiles/avifenc.dir/apps/avifenc.c.o CMakeFiles/avifenc.dir/apps/utf8.rc.obj -o avifenc.exe -Wl,--out-implib,libavifenc.dll.a -Wl,--major-image-version,0,--minor-image-version,0  libavif_apps.a  libavif_internal.a  G:/MABS/msys64/mingw32/lib/libyuv.a  -lm  G:/MABS/local32/lib/libdav1d.a  G:/MABS/local32/lib/librav1e.a  G:/MABS/local32/lib/libaom.a  G:/MABS/local32/lib/libpng.a  G:/MABS/msys64/mingw32/lib/libz.a  G:/MABS/msys64/mingw32/lib/libjpeg.a  -lmingwthrd  -lmingwthrd  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.2.0/../../../../i686-w64-mingw32/bin/ld.exe: G:/MABS/local32/lib/librav1e.a(rav1e.std-0f2dcfa9b7d06be0.std.b1ab508cbb5ea0e2-cgu.0.rcgu.o.rcgu.o): in function `ZN3std3sys3pal7windows1c11NtWriteFile17h3ec844bf04e2bc5fE':
/rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\sys\pal\windows/c.rs:309:(.text+0x1fdbc): undefined reference to `NtWriteFile@36'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.2.0/../../../../i686-w64-mingw32/bin/ld.exe: G:/MABS/local32/lib/librav1e.a(rav1e.std-0f2dcfa9b7d06be0.std.b1ab508cbb5ea0e2-cgu.0.rcgu.o.rcgu.o): in function `ZN3std3sys3pal7windows6handle6Handle17synchronous_write17haf3615c8b036eea9E':

/rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\sys\pal\windows/handle.rs:314:(.text+0x1fe50): undefined reference to `RtlNtStatusToDosError@4'

collect2.exe: error: ld returned 1 exit status
```

[logs.zip](https://github.com/AOMediaCodec/libavif/files/14970188/logs.zip) collected by M-AB-S

**Comment by LigH-de** [comment] 2024-04-14 10:03
Probably related to #2105

**Comment by wantehchang** [comment] 2024-04-14 14:06
Thanks for the bug report. Yes, this can be considered a duplicate of https://github.com/AOMediaCodec/libavif/issues/2105.

**Closed** 2024-04-14 20:54 UTC
